name: Java CI with Maven

on:
  [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/GameCode/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B package --file GameCode/pom.xml

      - name: Generate Test Report
        run: mvn test --file GameCode/pom.xml
      - name: Archive Test Report
        uses: actions/upload-artifact@v3
        with:
          name: Test Report
          path: GameCode/target/surefire-reports
      - name: Display Test Report
        run: cat GameCode/target/surefire-reports/*.xml

